import Head from "next/head"
import Header from "../header"
export function MainLayout ({children}:any) {
    return (
        <>
        <Head>
        <title>Market | Electronics</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header></Header>
        <main>
            {children}
        </main>
        </>
    )
}